# Zsh completions configuration
# This file provides additional completion definitions for many common
# commands that aren't included by default in Zsh's built-in completion system.

# Install the zsh-completions plugin using zinit. It provides:
# - Extensive collection of completion definitions for popular tools
# - Enhanced tab completion for commands like git, docker, npm, etc.
# - Automatically integrates with Zsh's completion system
# - Regular updates with new completion definitions
zinit light zsh-users/zsh-completions

# Configure the completion system to include uv and uvx completions
# generated by run_generate_uv_completions.sh
ZSH_COMPLETION_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/completions"
# Ensure the completion directory exists
[[ ! -d "$ZSH_COMPLETION_DIR" ]] && mkdir -p "$ZSH_COMPLETION_DIR"
# Add the custom completion directory to the function path. This allows Zsh to
# find and load completion functions stored there.
fpath=("$ZSH_COMPLETION_DIR" $fpath)

# Initialize the completions
zicompinit
zicdreplay
