name: Build Docker Image
description: Build Docker Image to verify Dockerfile works
runs:
  using: composite
  steps:
    - name: Build Docker Image
      shell: bash
      run: docker build -t dotfiles:testing-$(date +%Y%m%d%H%M%S) .
